export enum Cargo {
  FRONTEND_DEVELOPER = 'FRONTEND_DEVELOPER',
  BACKEND_DEVELOPER = 'BACKEND_DEVELOPER',
  FULLSTACK_DEVELOPER = 'FULLSTACK_DEVELOPER',
  MOBILE_DEVELOPER = 'MOBILE_DEVELOPER',
  DATA_ANALYST = 'DATA_ANALYST',
  DATA_ENGINEER = 'DATA_ENGINEER',
  DEVOPS_ENGINEER = 'DEVOPS_ENGINEER',
  QA_ENGINEER = 'QA_ENGINEER',
  UX_DESIGNER = 'UX_DESIGNER',
  PRODUCT_MANAGER = 'PRODUCT_MANAGER',
}
